name: Playwright Tests

# Trigger the workflow on specific events
on:
  push:
    branches:
      - master  # Trigger when code is pushed to the `master` branch
  pull_request:
    branches:
      - master  # Trigger on pull requests targeting the `master` branch

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Install Playwright browsers
    - name: Install Playwright Browsers
      run: npx playwright install

    # Run your tests
    - name: Run Playwright Tests
      run: npx playwright test

    # Upload test results and reports
    - name: Upload Playwright HTML report
      if: always()  # Always upload report, even if tests fail
      uses: actions/upload-artifact@v3
      with:
        name: playwright-report
        path: playwright-report
